
["Danger Close Server Configuration"]
	"ENTITIES TAKE BURNING DAMAGE FROM TORCHES" = false
	"ENTITIES TAKE BURNING DAMAGE FROM CAMPFIRES" = true
	"ENTITIES TAKE CUTTING DAMAGE FROM STONECUTTERS" = true
	"ENTITIES TAKE BURNING DAMAGE FROM BLAZES" = true
	"ENTITIES TAKE BURNING DAMAGE FROM MAGMA CUBES" = true
	"ENTITIES TAKE BURNING DAMAGE FROM MAGMA BLOCKS" = false
	"IS THE MOD ENABLED" = true

